const ticketData = [
    {
        id: '1',
        depPlace: "Zinder",
        destPlace: "Agadez",
        travelDate: "Sun Mar 31 2024",
        companyName: "Sonnef",
        travelDay: "10",
        seatType: "1",
        price: 25,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '2',
        depPlace: "Agadez",
        destPlace: "Dosso",
        travelDate: "Sun Mar 31 2024",
        companyName: "Rimbo",
        travelDay: "10",
        seatType: "1",
        price: 25,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '3',
        depPlace: "Dosso",
        destPlace: "Diffa",
        travelDate: "Sun Mar 31 2024",
        companyName: "Blabla",
        travelDay: "10",
        seatType: "1",
        price: 10000,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '50',
        depPlace: "Dosso",
        destPlace: "Diffa",
        travelDate: "Sun Mar 31 2024",
        companyName: "Blabla",
        travelDay: "10",
        seatType: "1",
        price: 10000,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '51',
        depPlace: "Dosso",
        destPlace: "Diffa",
        travelDate: "Sun Mar 31 2024",
        companyName: "Blabla",
        travelDay: "10",
        seatType: "1",
        price: 10000,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '53',
        depPlace: "Dosso",
        destPlace: "Diffa",
        travelDate: "Sun Mar 31 2024",
        companyName: "Blabla",
        travelDay: "10",
        seatType: "1",
        price: 10000,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '54',
        depPlace: "Dosso",
        destPlace: "Diffa",
        travelDate: "Sun Mar 31 2024",
        companyName: "Blabla",
        travelDay: "10",
        seatType: "1",
        price: 10000,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '55',
        depPlace: "Dosso",
        destPlace: "Diffa",
        travelDate: "Sun Mar 31 2024",
        companyName: "Blabla",
        travelDay: "10",
        seatType: "1",
        price: 10000,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '4',
        depPlace: "Dosso",
        destPlace: "Diffa",
        travelDate: "Sun Mar 31 2024",
        companyName: "Sonnef",
        travelDay: "10",
        seatType: "1",
        price: 12000,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '5',
        depPlace: "Dosso",
        destPlace: "Diffa",
        travelDate: "Sun Mar 31 2024",
        companyName: "Rimbo",
        travelDay: "10",
        seatType: "1",
        price: 10000,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '6',
        depPlace: "Dosso",
        destPlace: "Diffa",
        travelDate: "Sun Mar 31 2024",
        companyName: "Blabla",
        travelDay: "10",
        seatType: "1",
        price: 15000,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '7',
        depPlace: "Dosso",
        destPlace: "Diffa",
        travelDate: "Sun Mar 31 2024",
        companyName: "Sonnef",
        travelDay: "10",
        seatType: "1",
        price: 10000,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '8',
        depPlace: "Niamey",
        destPlace: "Zinder",
        travelDate: "Sun Mar 31 2024",
        companyName: "Rimbo",
        travelDay: "10",
        seatType: "1",
        price: 12500,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },

    {
        id: '9',
        depPlace: "Niamey",
        destPlace: "Zinder",
        travelDate: "Sun Mar 31 2024",
        companyName: "Blabla",
        travelDay: "10",
        seatType: "1",
        price: 12000,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '10',
        depPlace: "Niamey",
        destPlace: "Zinder",
        travelDate: "Sun Mar 31 2024",
        companyName: "Rimbo",
        travelDay: "10",
        seatType: "1",
        price: 12250,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '11',
        depPlace: "Agadez",
        destPlace: "Dakoro",
        travelDate: "Sun Mar 31 2024",
        companyName: "Sonnef",
        travelDay: "10",
        seatType: "1",
        price: 25,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '12',
        depPlace: "Tahoua",
        destPlace: "Mayahi",
        travelDate: "Sun Mar 31 2024",
        companyName: "Blabla",
        travelDay: "10",
        seatType: "1",
        price: 25,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '13',
        depPlace: "Niamey",
        destPlace: "Gaya",
        travelDate: "Sun Mar 31 2024",
        companyName: "Rimbo",
        travelDay: "10",
        seatType: "1",
        price: 25,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"
    },
    {
        id: '14',
        depPlace: "Niamey",
        destPlace: "Gaya",
        travelDate: "Sun Mar 31 2024",
        companyName: "Sonnef",
        travelDay: "10",
        seatType: "1",
        price: 25,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '15',
        depPlace: "Niamey",
        destPlace: "Gaya",
        travelDate: "Sun Mar 31 2024",
        companyName: "Rimbo",
        travelDay: "10",
        seatType: "1",
        price: 25,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '16',
        depPlace: "Niamey",
        destPlace: "Gaya",
        travelDate: "Sun Mar 31 2024",
        companyName: "Blabla",
        travelDay: "10",
        seatType: "1",
        price: 25,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '17',
        depPlace: "Niamey",
        destPlace: "Gaya",
        travelDate: "Sun Mar 31 2024",
        companyName: "Sonnef",
        travelDay: "10",
        seatType: "1",
        price: 25,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '18',
        depPlace: "Niamey",
        destPlace: "Gaya",
        travelDate: "Sun Mar 31 2024",
        companyName: "Rimbo",
        travelDay: "10",
        seatType: "1",
        price: 25,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '19',
        depPlace: "Zinder",
        destPlace: "Diffa",
        travelDate: "Sun Mar 31 2024",
        companyName: "Blabla",
        travelDay: "10",
        seatType: "1",
        price: 25,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '20',
        depPlace: "Zinder",
        destPlace: "Diffa",
        travelDate: "Sun Mar 31 2024",
        companyName: "Sonnef",
        travelDay: "10",
        seatType: "1",
        price: 25,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '21',
        depPlace: "Zinder",
        destPlace: "Diffa",
        travelDate: "Sun Mar 31 2024",
        companyName: "Rimbo",
        travelDay: "10",
        seatType: "1",
        price: 25,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '22',
        depPlace: "Zinder",
        destPlace: "Diffa",
        travelDate: "Sun Mar 31 2024",
        companyName: "Blabla",
        travelDay: "10",
        seatType: "1",
        price: 25,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '23',
        depPlace: "Zinder",
        destPlace: "Diffa",
        travelDate: "Sun Mar 31 2024",
        companyName: "Sonnef",
        travelDay: "10",
        seatType: "1",
        price: 25,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '24',
        depPlace: "Zinder",
        destPlace: "Diffa",
        travelDate: "Sun Mar 31 2024",
        companyName: "Rimbo",
        travelDay: "10",
        seatType: "1",
        price: 25,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '42',
        depPlace: "Zinder",
        destPlace: "Diffa",
        travelDate: "Sun Mar 31 2024",
        companyName: "Rimbo",
        travelDay: "10",
        seatType: "1",
        price: 25,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },

    {
        id: '25',
        depPlace: "Diffa",
        destPlace: "Zinder",
        travelDate: "Sun Mar 31 2024",
        companyName: "Blabla",
        travelDay: "10",
        seatType: "1",
        price: 25,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '26',
        depPlace: "Diffa",
        destPlace: "Zinder",
        travelDate: "Sun Mar 31 2024",
        companyName: "Rimbo",
        travelDay: "10",
        seatType: "1",
        price: 25,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '27',
        depPlace: "Gaya",
        destPlace: "Dakoro",
        travelDate: "Sun Mar 31 2024",
        companyName: "Sonnef",
        travelDay: "10",
        seatType: "1",
        price: 25,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '28',
        depPlace: "Gaya",
        destPlace: "Dakoro",
        travelDate: "Sun Mar 31 2024",
        companyName: "Blabla",
        travelDay: "10",
        seatType: "1",
        price: 25,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '29',
        depPlace: "Gaya",
        destPlace: "Dakoro",
        travelDate: "Sun Mar 31 2024",
        companyName: "Rimbo",
        travelDay: "10",
        seatType: "1",
        price: 25,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"
    },
    {
        id: '40',
        depPlace: "Dakoro",
        destPlace: "Gaya",
        travelDate: "Sun Mar 31 2024",
        companyName: "Rimbo",
        travelDay: "10",
        seatType: "1",
        price: 25,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"
    },
    {
        id: '30',
        depPlace: "Dakoro",
        destPlace: "Gaya",
        travelDate: "Sun Mar 31 2024",
        companyName: "Sonnef",
        travelDay: "10",
        seatType: "1",
        price: 25,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '31',
        depPlace: "Dakoro",
        destPlace: "Gaya",
        travelDate: "Sun Mar 31 2024",
        companyName: "Rimbo",
        travelDay: "10",
        seatType: "1",
        price: 25,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    },
    {
        id: '32',
        depPlace: "Dakoro",
        destPlace: "Gaya",
        travelDate: "Sun Mar 31 2024",
        companyName: "Blabla",
        travelDay: "10",
        seatType: "1",
        price: 25,
        availableSeats: 3,
        travelTimeHour: "10",
        travelTimeMinute: "30",
        durationHour: "4",
        durationMinute: "15"

    }

]

export default ticketData
